{
 "title": "o11y",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Successful responses 4xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (   sum(rate(http_requests_total{status=~\"4..\"}[5m]))     OR on() vector(0) ) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful responses 5xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (   sum(rate(http_requests_total{status=~\"5..\"}[5m]))     OR on() vector(0) ) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful responses 2xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"2..\"}[5m]))   / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  irate(http_requests_total[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(   0.5,  sum by(le)(rate(http_request_duration_seconds_bucket[5m])) )",
     "legendFormat": "50p"
    },
    {
     "expr": "1000 * histogram_quantile(   0.8,  sum by(le)(rate(http_request_duration_seconds_bucket[5m])) )",
     "legendFormat": "80p"
    },
    {
     "expr": "1000 * histogram_quantile(   0.95,  sum by(le)(rate(http_request_duration_seconds_bucket[5m])) )",
     "legendFormat": "95p"
    },
    {
     "expr": "1000 * histogram_quantile(   0.99,  sum by(le)(rate(http_request_duration_seconds_bucket[5m])) )",
     "legendFormat": "99p"
    }
   ]
  },
  {
   "title": "RPS /slow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/slow\"}[15s])",
     "legendFormat": "POST"
    }
   ]
  }
 ]
}