{
 "title": "pg_o11y",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"postgres\"}[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"postgres\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(   rate(pg_stat_database_xact_commit[1m]) +   rate(pg_stat_database_xact_rollback[1m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}