global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
